apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-protection
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TechOpsT/Enterprise-Platform-Lab.git
    targetRevision: main
    path: platform/velero/gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ServerSideApply=true]
