apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-home-lab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TechOpsT/Enterprise-Platform-Lab.git
    targetRevision: main
    path: charts/platform-home-lab
    helm:
      releaseName: platform-home-lab
      parameters:
        - name: api.image.repository
          value: ghcr.io/techopst/platform-api
        - name: api.image.tag
          value: 0051ca974e375a8085547e08abf41246104c35aa
        - name: api.image.pullPolicy
          value: Never
        - name: frontend.image.repository
          value: ghcr.io/techopst/platform-web
        - name: frontend.image.tag
          value: 0051ca974e375a8085547e08abf41246104c35aa
        - name: frontend.image.pullPolicy
          value: IfNotPresent
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
