controller:
  type: deployment
  replicas: 1

alloy:
  configMap:
    content: |-
      discovery.kubernetes "platform_pods" {
        role = "pod"

        namespaces {
          names = ["platform-lab"]
        }
      }

      discovery.relabel "platform_pods" {
        targets = discovery.kubernetes.platform_pods.targets

        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          target_label  = "namespace"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label  = "pod"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          target_label  = "container"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
          target_label  = "app"
        }
      }

      loki.source.kubernetes "platform_pods" {
        targets    = discovery.relabel.platform_pods.output
        forward_to = [loki.write.local.receiver]
      }

      loki.write "local" {
        endpoint {
          url = "http://loki-gateway.logging.svc.cluster.local/loki/api/v1/push"
        }
      }