namespace: platform-lab

api:
  replicaCount: 2
  image:
    repository: ghcr.io/techopst/platform-api
    tag: 1497a084e9eeff4ced554327529fda05c179b432
    pullPolicy: IfNotPresent
  resources:
    requests: { cpu: 100m, memory: 128Mi }
    limits: { cpu: 500m, memory: 256Mi }

frontend:
  replicaCount: 2
  image:
    repository: ghcr.io/techopst/platform-web
    tag: 1497a084e9eeff4ced554327529fda05c179b432
    pullPolicy: IfNotPresent
  resources:
    requests: { cpu: 50m, memory: 64Mi }
    limits: { cpu: 250m, memory: 128Mi }

postgres:
  image: postgres:16-alpine
  storage: 1Gi
  database: platform
  username: platform
  password: local-development-only

redis:
  image: redis:7-alpine

ingress:
  host: platform.local

autoscaling:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

data:
  enabled: false